#spring.application.name=MovieApi
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url = jdbc:mysql://localhost:3306/movieApidbFullstack?createDatabaseIfNotExist=true
#spring.datasource.username = nara
#spring.datasource.password = nara
#spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.validator.apply_to_ddl=false
#server.port=8081
#project.poster=posters/
#base.url="http://localhost:8081"
#spring.jpa.multipart.max-file-size=10MB
#spring.jpa.multipart.max-request-size=10MB
server:
  port: 8081
spring:
  datasource:
    username: nara
    password: nara
    url: jdbc:mysql://localhost:3306/movieApidbFullstack?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "mannepallinarasimha@gmail.com"
    password: "mpsponlvqskafvvh"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

project:
  poster: posters/

base:
  url: "http://localhost:8081"
